version: '3.9'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
    networks:
      - fastapi_app

  db:
    image: bitnami/postgresql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    env_file:
      - ./.env
    restart: always
    networks:
      - fastapi_app

networks:
  fastapi_app: